---
title: "Read in and MESA DNA methylation phenotype data"
subtitle: "the gct calculation loop sometimes fails, so this is converted to a separate markdown"
author: 
  - David lukacsovich^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

# Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(sesame)
  library(sesameData)
})

base_dir <- "~/TBL Dropbox/David Lukacsovich"
analysis_dir <- file.path(base_dir, "DATASET", "MESA")
raw_dir <- file.path(analysis_dir, "DNAm/raw/v4")
pheno_dir <- file.path(analysis_dir, "Phenotype/raw")
```

## Define Functions

```{r}
start_parallel <- function(parallel, cores) {
  if (parallel &&
      requireNamespace("doParallel", quietly = TRUE) &&
      requireNamespace("parallel", quietly = TRUE)) {
    if (Sys.info()["sysname"] == "Windows"){
      cluster <- parallel::makeCluster(cores)
      doParallel::registerDoParallel(cluster)
    } else {
      doParallel::registerDoParallel(cores)
    }
  } else {
    parallel = FALSE
  }
  
  parallel
}

stop_parallel <- function(parallel) {
  if (parallel &&
      requireNamespace("doParallel", quietly = TRUE) &&
      requireNamespace("parallel", quietly = TRUE)) {
    doParallel::stopImplicitCluster()
  }
  
  TRUE
}
```

# Read Data

## Get Phenotype

```{r load_pheno}
sample_df <- data.table::fread(
  file.path(
    raw_dir,
    "phg002108.v1.TOPMed_MESA_v4_Methylation.sample-info.MULTI",
    "phg002108.v1_release_manifest.txt"
  )
) %>%
  dplyr::mutate(sample = stringr::str_sub(.data$File_Name, 1, 24)) %>%
  dplyr::select(
    SAMPLE_ID = "Sample_ID", "Subject_ID", "sample", "Subject_Consent"
  )

dem_df <- data.table::fread(
    file.path(pheno_dir, "MesaTOPMed_PhenoWang_20240607/MesaTOPMed_PhenoWang_20240607.txt")
 ) %>%
  dplyr::rename(Subject_ID = "sidno")

pheno_df <- data.table::fread(
  file.path(pheno_dir, "phs001416.v4.p1.txt")
) %>%
  dplyr::select("SAMPLE_ID", "SEX")

pheno_df <- list.files(
  path = file.path(pheno_dir, "v4"),
  pattern = "HMB.*.txt.gz",
  full.names = TRUE
) %>% 
  purrr::map(.,~data.table::fread(., skip = 10)) %>%
  Reduce(rbind, .) %>%
  dplyr::left_join(
    sample_df, by = "SAMPLE_ID"
  ) %>%
  dplyr::left_join(pheno_df, by = "SAMPLE_ID") %>%
  dplyr::left_join(dem_df, by = "Subject_ID") %>%
  dplyr::mutate(CASI_LT86 = ifelse(
    is.na(.data$casisum5c),
    NA,
    ifelse(.data$casisum5c >= 86, 0, 1)
    )
  ) %>%
  dplyr::filter(.data$COLLECTION_VISIT == 5) %>%
  dplyr::filter(!is.na(.data$sample))

batch_df <- pheno_df %>%
  dplyr::select("SAMPLE_CONTAINER_ID") %>%
  dplyr::group_by(.data$SAMPLE_CONTAINER_ID) %>%
  dplyr::summarise(count = n()) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    batch = ifelse(.data$count > 10, .data$SAMPLE_CONTAINER_ID, "small_batch")
  )

pheno_df <- pheno_df %>%
  dplyr::left_join(batch_df %>% dplyr::select("SAMPLE_CONTAINER_ID", "batch"))
```

## Compute GCT score

```{r compute_gct}
idat_ls <- list.files(
  path = file.path(raw_dir),
  pattern = ".[.]idat",
  full.names = TRUE,
  recursive = TRUE
)
idat_ls <- gsub("_Grn.idat|_Red.idat", "", idat_ls) %>%
  unique()

idat_df <- data.frame(
  path = idat_ls,
  sample = basename(idat_ls),
  directory = dirname(idat_ls)
) %>%
  dplyr::filter(.data$sample %in% pheno_df$sample)

sesameData::sesameDataCache()

gct_ls <- c()
step_size <- 256
starts <- seq(1, nrow(idat_df), step_size)

for (start in starts) {
  end <- min(nrow(idat_df), start + step_size - 1)
  sample_ls <- idat_df$path[start:end]
  
  run_parallel <- start_parallel(TRUE, 32)
  batch_ls <- plyr::laply(
    sample_ls,
    .fun = function(idat) {
      sdf_df <- sesame::readIDATpair(
        prefix.path = idat,
        platform = "EPIC"
      )
      
      sesame::bisConversionControl(sdf_df)
    }, .parallel = TRUE
  )
  stop_parallel(run_parallel)
  
  gct_ls <- c(gct_ls, batch_ls)
}

pheno_df$gct_score <- gct_ls
```

# Save

## Save Full

```{r}
write.csv(
  pheno_df,
  file = file.path(pheno_dir, "DNAm_Data_Phenotypes.csv"),
  row.names = TRUE
)
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>
