---
title: "Read in and HRS NIAGADS DNA methylation data"
author: 
  - David lukacsovich^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

# Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(tidyr)
  library(minfi)
  library(wateRmelon)
  library(SummarizedExperiment)
})

base_dir <- "~/TBL Dropbox/David Lukacsovich"
analysis_dir <- file.path(base_dir, "DATASET", "HRS")
raw_dir <- file.path(analysis_dir, "DNAm", "raw")
data_dir <- file.path(analysis_dir, "DNAm", "preprocessing")
pheno_dir <- file.path(analysis_dir, "Phenotype", "NIAGADS")
```

# Read Data

## Get Phenotype

```{r load_pheno}
print(paste0("Get Phenotypes: ", Sys.time()))
pheno_df <- read.table(file.path(pheno_dir, "phenotype.tsv"), sep = "\t", header = TRUE)
param_df <- read.csv(file.path(pheno_dir, "sample_parameters.csv"))
match_df <- read.csv(file.path(pheno_dir,"idat_crosswalk.csv")) %>%
  dplyr::select(-"X")

pheno_df <- pheno_df %>%
  dplyr::left_join(match_df, by = c("SubjectID_Submitter" = "SubjectID")) %>%
  dplyr::left_join(param_df, by = "SubjectID_Submitter") %>%
  dplyr::arrange(.data$SubjectID_Submitter) %>%
  tidyr::separate("Sample_Plate", c("Sample_Plate", NA), sep = "/", remove = TRUE) %>%
  dplyr::mutate(
    Gender = ifelse(.data$Gender %in% c("M", "Male", "MALE"), "MALE", "FEMALE")
  )
```

## Get Idat Data

```{r load_idat}
RGSet <- minfi::read.metharray.exp(
  base = file.path(raw_dir, "IDAT_files"),
  recursive = TRUE,
  verbose = FALSE
)
RGSet <- RGSet[,pheno_df$IDATid]
```

## Create SummarizedExperiment

```{r create_dnam}
row.names(pheno_df) <- pheno_df$IDATid
dnam_data <- SummarizedExperiment::SummarizedExperiment(
  assays = list(dnam = RGSet),
  rowData = NULL,
  colData = pheno_df
)
```

# Add Annotation

## Get Bisulfite Scores

```{r pred_bisulfite}
dnam_data$Bisulfite <- wateRmelon::bscon(
  SummarizedExperiment::assays(dnam_data)$dnam
)
```

## Get Gender Prediction

```{r pred_gender}
assay_genome <- minfi::mapToGenome(
  SummarizedExperiment::assays(dnam_data)$dnam
)
assay_sex <- minfi::getSex(assay_genome)

dnam_data$Gender_Predicted <- ifelse(
  assay_sex$predictedSex %in% c("M", "Male", "MALE"), "MALE", "FEMALE"
)

dnam_data$Gender_Match <- ifelse(
  dnam_data$Gender == dnam_data$Gender_Predicted, "Yes", "No"
)
```

# Filter Samples

## Identify Samples to Filter

```{r}
pheno_df <- dnam_data %>%
  SummarizedExperiment::colData() %>%
  as.data.frame() %>%
  dplyr::mutate(
    Pass_Filter = .data$Bisulfite >= 85 & .data$Gender == .data$Gender_Predicted
  )
dnam_data$Pass_Filter <- pheno_df$Pass_Filter
```

## Save Full Unfiltered Phenotype

```{r}
pheno_df <- dnam_data %>%
  SummarizedExperiment::colData() %>%
  as.data.frame()
write.csv(
  pheno_df,
  file = file.path(data_dir, "DNAm_Data_All_Phenotypes.csv"),
  row.names = TRUE
)
```

## Filter Data

```{r}
dnam_data <- dnam_data[,dnam_data$Pass_Filter]
```

# Save

## Save Full

```{r}
saveRDS(dnam_data, file = file.path(raw_dir, "DNAm_Data.RDS"))
pheno_df <- dnam_data %>%
  SummarizedExperiment::colData() %>%
  as.data.frame()
write.csv(
  pheno_df,
  file = file.path(data_dir, "DNAm_Data_Phenotypes.csv"),
  row.names = TRUE
)
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>
