---
title: "Impute probes with detectionP > 0.01"
subtitle: "Look at autosomal probes"
author: 
  - David lukacsovich^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(methyLImp2)
})

base_dir <- "~/TBL Dropbox/David Lukacsovich"
analysis_dir <- file.path(base_dir, "DATASET", "HRS")
raw_dir <- file.path(analysis_dir, "DNAm", "raw")
data_dir <- file.path(analysis_dir, "DNAm", "preprocessing")
ref_dir <- file.path(analysis_dir, "DNAm", "ref_files")
result_dir <- file.path(analysis_dir, "analysis_results")
save_dir <- file.path(analysis_dir, "DNAm", "imputed")
```

# Load Data

## Load Data

```{r load_probes}
dnam_data <- readRDS(file.path(data_dir, "Preprocessed_Beta.RDS"))
pheno_df <- dnam_data %>%
  SummarizedExperiment::colData() %>%
  as.data.frame() %>%
  dplyr::mutate(batch = ifelse(
    .data$Sample_Plate == "Thyagarajan_Sample_144",
    "Thyagarajan_Sample_143",
    .data$Sample_Plate
  )
)
dnam_data$batch <- pheno_df$batch
probe_df <- dnam_data %>%
  SummarizedExperiment::rowData() %>%
  as.data.frame() %>%
  dplyr::rename(cpg = "Name") %>%
  dplyr::filter(!(.data$seqnames %in% c("chrM", "chrX", "chrY")))
dnam_data <- dnam_data[probe_df$cpg, ]
```

## Load Target Probes

```{r load_detp}
detp_df <- read.csv(file.path(data_dir, "detectionP_Failures.csv")) %>%
  dplyr::filter(.data$cpg %in% probe_df$cpg) %>%
  dplyr::filter(.data$sample %in% pheno_df$IDATid) %>%
  dplyr::filter(.data$detp >= 0.01)
```

# Impute Probes

## Define Functions

```{r impute_func}
get_beta_data <- function(dnam_data, detp_df) {
  beta_data <- SummarizedExperiment::assays(dnam_data)$dnam %>%
    t()
  
  samples <- row.names(beta_data)
  probes <- colnames(beta_data)
  
  detp_df <- detp_df %>%
    dplyr::filter(.data$sample %in% samples) %>%
    dplyr::filter(.data$cpg %in% probes)
  
  for (Sample in unique(detp_df$sample)) {
    cpgs <- detp_df %>%
      dplyr::filter(.data$sample == Sample) %>%
      dplyr::pull("cpg")
    
    beta_data[Sample, cpgs] <- NA
  }
  
  beta_data
}

get_probe_df <- function(dnam_data) {
  probe_df <- dnam_data %>%
    SummarizedExperiment::rowData() %>%
    as.data.frame() %>%
    dplyr::select(cpg = "Name", chr = "seqnames")
  
  probe_df
}

impute_beta <- function(beta_data, probe_df, batches) {
  samples <- row.names(beta_data)
  probes <- colnames(beta_data)
  
  beta_data <- methyLImp2::methyLImp2(
    beta_data,
    type = "user",
    annotation = probe_df,
    BPPARAM = BiocParallel::SnowParam(workers = 22, exportglobals = FALSE),
    groups = batches,
    overwrite_res = FALSE
  )
  
  colnames(beta_data) <- probes
  row.names(beta_data) <- samples
  
  beta_data
}

impute_batches <- function(dnam_data, detp_df, batches) {
  batch_ls <- dnam_data %>%
    SummarizedExperiment::colData() %>%
    as.data.frame() %>%
    dplyr::pull("batch")
  
  dnam_data <- dnam_data[,batch_ls %in% batches]
  beta_data <- get_beta_data(dnam_data, detp_df)
  probe_df <- get_probe_df(dnam_data)
  batches <- dnam_data %>%
    SummarizedExperiment::colData() %>%
    as.data.frame() %>%
    dplyr::pull("batch")
  beta_data <- impute_beta(beta_data, probe_df, batches)
  
  dnam_data <- SummarizedExperiment::SummarizedExperiment(
    assays = list(dnam = t(beta_data)),
    rowData = dnam_data %>%
      SummarizedExperiment::rowData() %>%
      as.data.frame(),
    colData = dnam_data %>%
      SummarizedExperiment::colData() %>%
      as.data.frame()
  )
  
  dnam_data
}
```

## Impute in Batches

```{r impute_run}
batch_ls <- dnam_data %>%
  SummarizedExperiment::colData() %>%
  as.data.frame() %>%
  dplyr::pull("batch") %>%
  unique()

step_size <- 2
starts <- seq(1, length(batch_ls), step_size)

for (index in 1:length(starts)) {
  start <- starts[[index]]
  end <- min(start + step_size - 1, length(batch_ls))
  batches <- batch_ls[start:end]
  
  batch_data <- impute_batches(dnam_data, detp_df, batches)
  savename <- sprintf("Imputed_Autosomal_%02d.RDS", index)
  
  saveRDS(batch_data, file.path(save_dir, savename))
  rm(batch_data)
  gc()
}
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>

