---
title: "01e_evaluate_batch_BEclear"
output: html_document
date: "2025-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(BEclear)
  library(SummarizedExperiment)
  library(parallel)
  library(doParallel)
  library(BiocParallel)
})

base_dir <- "~/TBL Dropbox/David Lukacsovich"
analysis_dir <- file.path(base_dir, "DATASET", "HRS")
data_dir <- file.path(analysis_dir, "datasets")
norm_dir <- file.path(data_dir, "normalized")
batch_dir <- file.path(data_dir, "batch_corrected")
be_dir <- file.path(data_dir, "be_summary")
```

# Calculate BEclear Evaluation

## Define Functions

```{r}
prepare_dnam_metadata <- function(dnam_data, dataset) {
  if (dataset == "ADNI") {
    dnam_data$age_split_by_tertiles <- ntile(dnam_data$age_at_visit, 3)
  } else if (dataset == "AIBL") {
    dnam_data$age_split_by_tertiles <- ntile(dnam_data$pred_age_elastic, 3)
  } else if (dataset == "FHS") {
    dnam_data$age_split_by_tertiles <- ntile(dnam_data$Age_at_collection, 3)
    batches <- dnam_data$batch
    batches <- ifelse(batches == "B0019", "B0018", batches)
    dnam_data$batch <- batches
  } else if (dataset == "MESA") {
    dnam_data$race <- as.character(dnam_data$race1c)
  }
  
  dnam_data
}

read_beclear_input <- function(dataset, batched = TRUE) {
  if (batched) {
    fname <- file.path(batch_dir, paste0(dataset, "_Batched.RDS"))
  } else {
    fname <- file.path(norm_dir, paste0(dataset, "_Autosomal.RDS"))
  }
  
  dnam_data <- readRDS(fname) %>%
    prepare_dnam_metadata(dataset)
  
  dnam_data
}

calculate_batch_effect <- function(dnam_data) {
  beta_data <- SummarizedExperiment::assays(dnam_data)$dnam
  sample_df <- dnam_data %>%
    SummarizedExperiment::colData() %>%
    as.data.frame() %>%
    dplyr::select(sample_id = "sample", batch_id = "batch") %>%
    dplyr::mutate(batch_id = as.character(.data$batch_id))
  
  be_res <- BEclear::calcBatchEffects(
    beta_data,
    samples = sample_df,
    adjusted = TRUE,
    method = "fdr",
    BPPARAM = BiocParallel::MulticoreParam(16)
  )
  
  be_res
  
  # Summarize median comparison
  BE_summ <- BEclear::calcSummary(be_res$med, be_res$pval)
  
  # Calculate score
  BE_score <- BEclear::calcScore(
    data = beta_data,
    samples = sample_df,
    BE_summ
  )
  
  list(BE_summ = BE_summ, BE_score = BE_score)
}

get_savename <- function(dataset, label, batched = TRUE) {
  if (batched) {
    fname <- paste0(dataset, "_batch_eval.xlsx")
  } else {
    fname <- paste0(dataset, "_base_eval.xlsx")
  }
  
  savename <- file.path(be_dir, fname)
  
  savename
}

summarise_and_save <- function(dnam_data, savename) {
  BE_res <- calculate_batch_effect(dnam_data)
  writexl::write_xlsx(
    list(summary = BE_res$BE_summ, score = BE_res$BE_score),
    file.path(savename)
  )
}

be_summarise <- function(dataset, replace = FALSE) {
  
  dnam_data <- read_beclear_input(dataset, batched = TRUE)
  
  savename <- get_savename(dataset, batched = TRUE)
  if (replace | !(file.exists(savename))) {
    summarise_and_save(dnam_data, savename)
  }
  
  dnam_data <- read_beclear_input(dataset, batched = FALSE)
  
  savename <- get_savename(dataset, batched = FALSE)
  if (replace | !(file.exists(savename))) {
    summarise_and_save(dnam_data, savename)
  }
}
```

## Run for data and batch-correction

```{r}
be_summarise("AIBL", replace = TRUE)
be_summarise("ADNI", replace = TRUE)
be_summarise("FHS", replace = TRUE)
be_summarise("MESA", replace = TRUE)
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>
