---
title: "Evaluate batch-correction using Harman method"
subtitle: "Using BEclear summaries, hecking for keeping sex-effects, and keeping sex+DX-effects"
author: 
  - David lukacsovich^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(ggplot2)
  library(ggpubr)
  library(SummarizedExperiment)
})

base_dir <- "~/TBL Dropbox/David Lukacsovich"
analysis_dir <- file.path(base_dir, "DATASET", "HRS")
data_dir <- file.path(analysis_dir, "datasets")
norm_dir <- file.path(data_dir, "normalized")
batch_dir <- file.path(data_dir, "batch_corrected")
be_dir <- file.path(data_dir, "be_summary")
```

# Define Functions

## Read Data

```{r}
get_excel_name <- function(dataset, batched = TRUE) {
  if (batched) {
    fname <- paste0(dataset, "_batch_eval.xlsx")
  } else {
    fname <- paste0(dataset, "_base_eval.xlsx")
  }
  
  savename <- file.path(be_dir, fname)
  
  savename
}

read_summaries <- function(dataset, batched = TRUE) {
  savename <- get_excel_name(dataset, batched = batched)
  readxl::read_excel(savename, sheet = "summary") %>%
    as.data.frame()
}

get_condition_summaries <- function(dataset) {
  rbind(
    read_summaries(dataset, batched = FALSE) %>%
      dplyr::mutate(Status = "Before Batch Correction"),
    read_summaries(dataset, batched = TRUE) %>%
      dplyr::mutate(Status = "After Batch Correction")
  )
}
```

## Plot Data

```{r}
add_counts <- function(summary_df) {
  count_df <- summary_df %>%
    dplyr::group_by(.data$Status) %>%
    dplyr::summarise(count = n()) %>%
    dplyr::ungroup()
  
  summary_df %>%
    dplyr::left_join(count_df, by = "Status") %>%
    dplyr::mutate(Status = paste0(.data$Status, " (n = ", .data$count, ")"))
}

plot_summary <- function(summary_df, title) {
  summary_df <- summary_df %>%
    dplyr::mutate(batch_id = factor(.data$batch_id)) %>%
    add_counts()
  
  ggplot2::ggplot(summary_df, mapping = ggplot2::aes(x = batch_id)) + 
    ggplot2::geom_bar(aes(fill = Status), position = "dodge") + 
    ggplot2::theme_classic() + 
    ggplot2::theme(legend.position = "top") + 
    ggplot2::ggtitle(title)
}

plot_condition <- function(dataset) {
  summary_df <- get_condition_summaries(dataset)

  plot_summary(summary_df, dataset)
}
```

# Create Plots

```{r fig.width = 8, fig.height = 5}
plot_condition("ADNI")
plot_condition("AIBL")
plot_condition("FHS")
plot_condition("MESA")
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>
